Develop save system
Tiny-Metro/Tiny-Metro pull request #242
Opened 2023-07-11 07:29 UTC by yoon-H

2023-07-11 07:43 UTC, ruru14 commented on Source/TinyMetro/Private/Timer/Timer.cpp
> +		SaveManagerRef->SaveAllActor();
이부분에 넣는것보단, SaveManager가 Timer를 참조하는게 좋겠습니다.

```
SaveManager::BeginPlay() {
  GameModeRef = ~~~ ;
  GameModeRef->GetTimer()->WeeklyTask.AddDynamic(&this, SaveManager::SaveAllActor());
  ~~~~
}
```
위와 같은 느낌으로요

2023-07-11 07:45 UTC, ruru14 commented on Source/TinyMetro/Private/SaveSystem/TMSaveManager.cpp
아래 Timer쪽 코멘트 참조하셔서, BeginPlay에 자동저장 기능 추가해주세요

2023-07-11 07:46 UTC, ruru14 commented on Source/TinyMetro/Private/SaveSystem/TMSaveManager.cpp
> +	FString fileName = EnumPtr->GetNameStringByIndex((int32)ActorType);
이부분 switch문 쓰실 줄 알고 enum기반으로 변경해서 확장성을 높혀보자고 하려했는데, 이미 해주셨네요

잘하셨습니다.

2023-07-11 07:48 UTC, ruru14 commented on Source/TinyMetro/Public/Timer/Timer.h
> +	class ATMSaveManager* SaveManagerRef;
Timer에 SaveManagerRef가 있어야 하는 이유가, WeeklyTask 아래쪽에 Save를 호출해서 자동저장을 구현해야 하기 때문이었죠

위 코멘트대로 SaveManager측에서 Delegate에 바인딩해주면, 이부분은 없어도 될 것 같습니다.

2023-07-11 07:48 UTC, ruru14 requested changes
코멘트 참조하셔서 수정 부탁드릴께요

- [ ] Timer.h에서 SaveManagerRef 제거
- [ ] SaveManager에서 TimerRef획득 및 WeeklyTask에 바인딩
- [ ] 깔끔해진 코드를 보며 으쓱 한번
- [ ] 여유가 된다면 주석이 필요한 부분을 생각해보기

2023-07-11 09:49 UTC, yoon-H commented
ad7610008e1e52657eafc3056e75e96ef5b99004

2023-07-12 07:59 UTC, ruru14 approved these changes

2023-07-12 07:59 UTC, merged