[Fix] fix camera bugs
Tiny-Metro/Tiny-Metro pull request #283
Opened 2023-08-24 18:12 UTC by AzureSoda

2023-08-25 04:23 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeLocation(FVector(0, 0, 6000.f)); //초기위치,높이 설정
SetRelativeLocation과 SetWorldLocation의 차이점을 아시나요?

2023-08-25 04:23 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
SetRelativeLocation / Rotation과 SetWorldLocation / Rotation의 차이점을 아시나요?

2023-08-25 04:24 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  				playerController->GetViewportSize(screenWidth, screenHeight);
해당 값 상황마다 어떻게 변화하는지 검사해보셨을까요?

2023-08-25 04:26 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					DeltaMouse *= RotationSpeed * GetWorld()->GetDeltaSeconds();
GetDeltaSeconds함수의 용도와, 해당 함수를 사용한 이유가 무엇인가요?

2023-08-25 04:29 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					PanForward(MovementInput.X);
PanRight, PanForward는 InputComponent에 이미 바인딩 되어있는데, 이 코드의 목적은 무엇인가요?

2023-08-25 04:30 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			AddMovementInput(FRotationMatrix(GetControlRotation()).GetScaledAxis(EAxis::X), 1000000000000 * magnitude * ZoomRate * GetWorld()->GetDeltaSeconds());
1000000000000이라는 숫자의 역할이 무엇인가요?

2023-08-25 04:30 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			if (playerController->IsInputKeyDown(EKeys::RightMouseButton))  // 오른쪽 마우스 버튼이 눌려있는지 확인
EngageRotation은 InputComponent에 이미 매핑이 되어있습니다. 마우스 클릭을 확인하는 이유가 무엇인가요?

2023-08-25 04:35 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  			FVector2D mouseLocation;
해당 변수 mouseLocation및 하단의 DeltaMouse, NewRotation등등의 변수를 Tick에서 새로 선언해주는 이유가 무엇인가요?

2023-08-25 04:36 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					float RotationSpeed = 1.0f;  // 회전 속도 조절
해당 변수는 회전 속도 조절 변수인데 왜 클래스 필드에서 혼자 빠져나왔나요?

2023-08-25 04:38 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +		APlayerController* playerController = Cast<APlayerController>(GetController());
Tick등 해당 코드와 유사한 부분에 대한 전반적인 질문입니다.
Pawn에 이미 Controller 필드가 있는데 지속적으로 참조해서 캐스팅하는 이유가 있을까요?

2023-08-25 04:40 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
해당 코드에서 발생할 수 있는 예외상황이 뭐가 있을까요?

2023-08-25 04:42 UTC, ruru14 commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
아래 함수, 변수들에 UFUNCTION, UPROPERTY를 선언하지 않은 이유가 있을까요?

2023-08-25 12:37 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
"SetRelative" 접두사가 있는 함수들은 현재 상태를 기준으로 한 상대적인 변화를 적용하고
"SetWorld" 접두사가 있는 함수들은 월드 공간에서 절대적인 변화를 적용하여 위치와 회전 값을 설정하는데
원래 코드에서 SetRelativeLocation을 사용해서 그것에 맞춰서 SetRelativeLocation을 사용했습니다.

2023-08-25 12:39 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					DeltaMouse *= RotationSpeed * GetWorld()->GetDeltaSeconds();
DeltaMouse *= RotationSpeed * GetWorld()->GetDeltaSeconds(); 코드에서 마우스 움직임인 DeltaMouse 값에 회전 속도 RotationSpeed와 GetDeltaSeconds() 값을 곱하여 실제 움직임에 반영하기 위해서 사용했고 이렇게 함으로써 회전 속도와 프레임 간 시간 간격을 고려하여 움직임의 변화를 조절할 수 있습니다.

2023-08-25 12:42 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					PanForward(MovementInput.X);
저부분을 추가하지 않으니까 패닝이 반대로 되어서 상하좌우 패닝을 제대로 하기 위해서 추가했습니다.

2023-08-25 12:42 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			AddMovementInput(FRotationMatrix(GetControlRotation()).GetScaledAxis(EAxis::X), 1000000000000 * magnitude * ZoomRate * GetWorld()->GetDeltaSeconds());
줌값이 너무 작아서 값을 크게 하기 위해서 숫자 1000000000000를 추가했습니다

2023-08-25 12:47 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			if (playerController->IsInputKeyDown(EKeys::RightMouseButton))  // 오른쪽 마우스 버튼이 눌려있는지 확인
처음에 EngagerRotation으로 들어갈때 마우스 클릭상태를 확인해서 마우스 오른쪽 버튼이 눌렸을때 EngageRotation이 되도록 만들었기 때문입니다.

2023-08-25 12:49 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  			FVector2D mouseLocation;
Tick 함수가 실행될 때마다 마우스 커서의 위치를 얻어와 저장하고 처리하기 위해서 새로 선언했습니다

2023-08-25 12:54 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
Null Pointer Exception 일 경우의 예외상황이 생길 수 있을 것 같습니다

2023-08-25 12:55 UTC, AzureSoda commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
함수 기능 구현에 집중하느라 UFUNCTION, UPROPERTY까지는 고려 못했는데 혹시 UFUNCTION, UPROPERTY로 선언한 것과 선언하지 않았을 때의 차이가 있을까요?

2023-08-25 13:06 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  				playerController->GetViewportSize(screenWidth, screenHeight);
screenwidth, screenheight  값을 변경해도 뷰포트에 보이는 것에 영향이 없었습니다

2023-08-25 13:08 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +		APlayerController* playerController = Cast<APlayerController>(GetController());
해당 부분을 빠뜨리게 되면 식별자 playercontroller가 없다는 오류가 나오게 됩니다. 마우스와 관련된 함수를 사용하기 위해서 playerController가 필요합니다

2023-08-25 13:16 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					float RotationSpeed = 1.0f;  // 회전 속도 조절
화면 회전 함수를 기존에서 바꾸게 되었는데 바꾸면서 회전 속도 조절을 저 방식으로 하니까 값이 제대로 바뀌어서 저렇게 하게 되었습니다.

2023-08-25 13:59 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  				playerController->GetViewportSize(screenWidth, screenHeight);
변화하지 않는 값이면 추적할 필요가 없는데 왜 Tick에서 계속 추적하나요?

2023-08-25 14:00 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					DeltaMouse *= RotationSpeed * GetWorld()->GetDeltaSeconds();
프레임 간 시간 간격은 Tick의 DeltaSeconds에 이미 있는데, GetDeltaSeconds가 필요없지않을까요?

2023-08-25 14:01 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  				playerController->GetViewportSize(screenWidth, screenHeight);
다시 확인해보고 지우겠습니다

2023-08-25 14:01 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					PanForward(MovementInput.X);
패닝이 반대로 되는것과 Tick에서 위 함수들을 호출하는게 무슨 관계가 있을까요?

2023-08-25 14:01 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			AddMovementInput(FRotationMatrix(GetControlRotation()).GetScaledAxis(EAxis::X), 1000000000000 * magnitude * ZoomRate * GetWorld()->GetDeltaSeconds());
해당 코드의 다른 변수들의 목적과 추정 값 범위가 어느정도인가요?

2023-08-25 14:01 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			if (playerController->IsInputKeyDown(EKeys::RightMouseButton))  // 오른쪽 마우스 버튼이 눌려있는지 확인
EngageRotation은 이미 오른쪽 마우스 버튼에 바인딩되어있습니다.

2023-08-25 14:02 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  			FVector2D mouseLocation;
변수가 매번 생성되고 파괴되는게 비효율적이지 않을까요?

2023-08-25 14:03 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					float RotationSpeed = 1.0f;  // 회전 속도 조절
해당 값 변동 없는 상수인데, Tick에 있을 필요가 있을까요?

2023-08-25 14:03 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +		APlayerController* playerController = Cast<APlayerController>(GetController());
playerController를 받아오는 코드가 산재해있는 이유에 대한 질문입니다. 다시 답변 부탁드려요

2023-08-25 14:04 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
GetActorRotation는 포인터를 반환하는 함수가 아닙니다

2023-08-25 14:04 UTC, ruru14 commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
UFUNCTION과 UPROPERTY의 역할이 뭔가요?

2023-08-25 14:12 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			AddMovementInput(FRotationMatrix(GetControlRotation()).GetScaledAxis(EAxis::X), 1000000000000 * magnitude * ZoomRate * GetWorld()->GetDeltaSeconds());
magnitude: 마우스 휠의 값
MinZoom: 최소 줌의 범위
MaxZoom: 최대 줌의 범위
ZoomRate: 줌 되는 정도
입니다

2023-08-25 14:13 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
카메라가 없어지는 경우에 예외 상황이 생길 것 같습니다

2023-08-25 14:16 UTC, AzureSoda commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
UFUCTION은 블루프린트 비주얼 스크립팅 시스템 안에서 호출 또는 오버라이드 가능합니다.
UPROPERTY는 UPROPERTY 내에 프로퍼티 지정자를 나열함으로써, 해당 프로퍼티가 엔진과 에디터의 다양한 부분과 상호작용할 수 있습니다.

2023-08-25 14:30 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					PanForward(MovementInput.X);
저 부분이 panright 동작과 panforward 동작을 하는 부분입니다. 사용자 입력에 따른 카메라의 패닝 동작을 처리하는 부분입니다. Tick으로 계속해서 마우스의 위치를 가져와서 이동해야하기 때문에 Tick에서 호출하도록 만들었습니다

2023-08-25 15:06 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					DeltaMouse *= RotationSpeed * GetWorld()->GetDeltaSeconds();
FVector2D DeltaMouse = mouseScreenLocationGrab - mouseLocation;
float RotationSpeed = 1.0f;  // 회전 속도 조절
DeltaMouse *= RotationSpeed * DeltaSeconds; 로 수정하겠습니다

2023-08-25 15:06 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					float RotationSpeed = 1.0f;  // 회전 속도 조절
확인해보고 지우겠습니다

2023-08-26 01:12 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					PanForward(MovementInput.X);
그러면 InputComponent에서 바인딩한 PanRight와 PanForward는 무슨 역할을 하나요?

2023-08-26 01:13 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			AddMovementInput(FRotationMatrix(GetControlRotation()).GetScaledAxis(EAxis::X), 1000000000000 * magnitude * ZoomRate * GetWorld()->GetDeltaSeconds());
추정 값 범위와 AddMovementInput함수의 구체적인 기능에 대해 설명해주세요

2023-08-26 01:16 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
카메라가 없어지면 해당 코드가 호출되지 않습니다

2023-08-26 01:20 UTC, ruru14 commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
해당 함수 및 변수들의 호출자와 확장성에 대해서 고려해보셨나요?

2023-08-26 08:03 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
SetRelativeLocation: Set the location of the component relative to its parent / 부모를 기준으로 컴포넌트의 위치를 설정합니다.
SetRelativeRotation: Set the rotation of the component relative to its parent / 부모를 기준으로 컴포넌트의 회전을 설정합니다.
SetWorldLocation: Put this component at the specified location in world space. Updates relative location to achieve the final world location. 이 컴포넌트를 월드 스페이스의 지정된 위치에 배치합니다. 최종 월드 위치를 얻기 위해 상대 위치를 업데이트합니다.
SetWorldRotation: Put this component at the specified rotation in world space. / 이 컴포넌트를 월드 스페이스에서 지정된 로테이션에 배치합니다
두개의 차이는 레벨이 기준이냐 부모 컴포넌트가 기준이냐의 차이입니다

2023-08-26 08:28 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
playerController를 받아오지 못할 때 예외상황이 생길 것 같습니다

2023-08-26 08:28 UTC, AzureSoda commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
다른 외부에서 불리지 않고 회전하는 함수내에서만 기능할 것이라고 생각했습니다.

2023-08-26 08:30 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					PanForward(MovementInput.X);
해당 부분 확인해본 결과 없애도 지장이 없어서 지우겠습니다

2023-08-26 08:34 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
해당 코드는 카메라 초기위치 지정하는 코드인데, 그러면 World기준 좌표가 맞지 않을까요?

2023-08-26 08:35 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
네 월드로 수정하겠습니다 혹시 저기 relativeroation도 worldrotation으로 수정할까요?

2023-08-26 08:35 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
playerController는 이미 위쪽에서 null을 확인합니다.

2023-08-26 08:38 UTC, ruru14 commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
코멘트에 있는 함수 한정이 아니라, 다른 함수도 포함한 질문입니다.

2023-08-26 09:13 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
RelativeRotation으로 지정한 특별한 이유가 있나요?

2023-08-26 10:36 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
초기에 찾아본 코드가 relativerotation으로 되어있어서 그렇게 한건데 수정하겠습니다

2023-08-26 10:38 UTC, AzureSoda commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
확장성에 대해서는 카메라 관련 함수들은 카메라를 조작하는 데에서만 활용된다고 생각했습니다.

2023-08-26 10:42 UTC, ruru14 commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
초기 기획에 카메라 이동시키는 함수가 외부에서 사용된다고 하지 않았었나요?

2023-08-26 11:21 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
bEnableMouseOverEvents 과 관련한 문제가 생길때 예외사항이 생길 것 같습니다

2023-08-26 11:22 UTC, AzureSoda commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
Jumpto에 UFuction을 붙이겠습니다

2023-08-26 12:01 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  			FVector2D mouseLocation;
rtscamera.h로 변수를 옮겨 해결했습니다

2023-08-26 12:04 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +					float RotationSpeed = 1.0f;  // 회전 속도 조절
RtsCamera.h에서 UProperty로 빼서 변경가능하도록 했습니다

2023-08-26 15:09 UTC, AzureSoda commented on Source/TinyMetro/Public/Camera/RtsCamera.h
>  	void PanForward(float magnitude);
포인트를 쓰는 변수들 UProperty 처리하였고 다른 곳에서도 사용하는 Jumpto 함수도 UFuction으로 만들었습니다

2023-08-26 15:10 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	CustomCollisionComponent->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
world로 수정한뒤에 위치를 게임 시작하면 실행하는 beginplay로 위치 변경하였습니다.

2023-08-26 15:12 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			AddMovementInput(FRotationMatrix(GetControlRotation()).GetScaledAxis(EAxis::X), 1000000000000 * magnitude * ZoomRate * GetWorld()->GetDeltaSeconds());
해당 부분들의 필요한 숫자들을 없애고 변수들을 정리하였습니다.

2023-08-26 15:12 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
>  			FVector2D mouseLocation;
변수들의 위치를 RtsCamera.h로 이동하여 전역변수로 만들어서 사용하는 것으로 변경하였습니다.

2023-08-26 15:13 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +		APlayerController* playerController = Cast<APlayerController>(GetController());
캐스팅하는 것의 비용이 크다는 것을 알게되어서
캐스팅하는 것을 줄이고자 변수를 RtsCamera.h로 이동하여서 전역변수로 사용가능하게 변경하였습니다

2023-08-26 15:14 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				InitialRotation = GetActorRotation();
카메라가 회전 중 돌아오는 과정에서 빠르게 마우스 오른쪽 버튼을 누를 경우 초기화 위치의 문제가 있습니다

2023-08-27 08:22 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +#include "..\..\Public\Camera\RtsCamera.h"
왜넣었나요?

2023-08-27 08:24 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			playerController->GetViewportSize(screenWidth, screenHeight);
해당 값 항상 고정되있는 값 아닌가요?

2023-08-27 08:25 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				//MovementInput.Y -= 1;
코드 안 지우고 주석처리 해둔 이유가 있을까요?

2023-08-27 08:25 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				PanLeft(mousecheck);
mousecheck의 역할이 뭘까요?

2023-08-27 08:26 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +#include "..\..\Public\Camera\RtsCamera.h"
#include "..\..\Public\Camera\RtsCamera.h" 이 부분 말씀하시는 거죠? 어제 코드작성하다 보니 자동으로 들어가 있던데 지우겠습니다

2023-08-27 08:30 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				PanLeft(mousecheck);
mousecheck 변수는 마우스 상태를 나타내는 불 값으로 마우스가 어떤 상태인지 값을 받아옵니다

2023-08-27 08:31 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				//MovementInput.Y -= 1;
혹시 몰라서 이해를 돕고자 넣었는데 지우겠습니다

2023-08-27 08:34 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			playerController->GetViewportSize(screenWidth, screenHeight);
게임을 실행하는 해상도 크기마다 달라진다고 알고있습니다 그래서 저것을 받아와야한다고 알고있습니다

2023-08-27 08:35 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			playerController->GetViewportSize(screenWidth, screenHeight);
게임 실행 시의 해상도를 Tick에서 계속 검사할 필요가 있을까요?

2023-08-27 08:35 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				PanLeft(mousecheck);
마우스 상태와 Pan함수의 동작에 무슨 관계가 있죠?

2023-08-27 08:36 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			playerController->GetViewportSize(screenWidth, screenHeight);
아 beginplay로 이동시키겠습니다

2023-08-27 10:50 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +				PanLeft(mousecheck);
함수에서 필요 없는 변수를 지웠습니다

2023-08-27 11:17 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			playerController->GetViewportSize(screenWidth, screenHeight);
이전 리뷰에 수정했다고 하지 않았나요?

2023-08-27 11:17 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			FVector MovementInput = FVector::ZeroVector;
해당 변수 어디서 사용되고 있을까요?

2023-08-27 11:18 UTC, ruru14 commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	screenWidth, screenHeight;
의미있는 코드인가요?

2023-08-27 11:23 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +			playerController->GetViewportSize(screenWidth, screenHeight);
지웠습니다

2023-08-27 11:27 UTC, AzureSoda commented on Source/TinyMetro/Private/Camera/RtsCamera.cpp
> +	screenWidth, screenHeight;
screenWidth, screenHeight; 이부분 필요 없어서 지웠습니다

2023-08-27 11:42 UTC, ruru14 requested changes
코드 린팅 다시해주세요

2023-08-27 12:29 UTC, ruru14 approved these changes

2023-08-27 12:30 UTC, merged